/**
 * Exercise Timer
 * Copyright (c) 2026 Wayne Davies
 * MIT License. See LICENSE in the project root.
 */

import type { Plugin } from 'vite'
import { defineConfig } from 'vitest/config'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'

/*
 * The copyright notice, carried into the built bundle.
 *
 * Every source file has this header, but a plain comment does not survive
 * minification, so the deployed app used to ship with no notice at all. MIT
 * asks for the notice to travel with the code, and the deployed bundle is the
 * only copy most people will ever hold.
 *
 * `/*!` marks it as a legal comment, which esbuild and every other minifier
 * keep by convention. The licence URL is absolute because a bundle has no
 * project root to point at, and the carve-out is repeated because someone
 * reading only this would otherwise assume the pictures came with the code.
 *
 * The service worker and the workbox runtime are generated by vite-plugin-pwa
 * after this point, so they are not covered. That is correct: they are not our
 * code.
 */
const NOTICE = `/*!
 * Exercise Timer
 * Copyright (c) 2026 Wayne Davies
 *
 * MIT License. https://github.com/waynetd777/exercise-timer/blob/main/LICENSE
 * The exercise illustrations are third-party and NOT covered by it.
 */`

/*
 * Prepends the notice to every built script and stylesheet.
 *
 * This is done in `generateBundle` rather than with Rollup's `output.banner` or a
 * `renderChunk` hook, and the reason is not obvious: BOTH of those run before Vite
 * minifies. Vite drives esbuild with `legalComments: 'none'`, so a banner added
 * earlier is deleted on the way out, `/*!` or not. `generateBundle` runs after
 * every chunk has been rendered and minified, and before anything is written, so
 * the notice survives and the service worker still precaches what is on disk.
 *
 * A consequence to know about: the content hash in each filename was computed
 * before this ran, so it does not cover the notice. Harmless, because the notice
 * is a constant. The hash still changes whenever the code does, which is the only
 * thing it is there for.
 */
function licenceNotice(): Plugin {
  return {
    name: 'licence-notice',
    enforce: 'post',
    apply: 'build',
    generateBundle(_options, bundle) {
      for (const file of Object.values(bundle)) {
        if (file.type === 'chunk') {
          file.code = `${NOTICE}\n${file.code}`
        } else if (file.fileName.endsWith('.css') && typeof file.source === 'string') {
          file.source = `${NOTICE}\n${file.source}`
        }
      }
    },
  }
}

// `base` is driven by an env var so the same build works on a root-domain host
// and on a subpath host (GitHub Pages -> /exercise-timer/). All bundled asset
// paths must go through import.meta.env.BASE_URL, never a hardcoded leading
// slash.
export default defineConfig({
  base: process.env.VITE_BASE ?? '/',
  /*
   * The build's own date, shown beside the version on the home screen. The
   * version is bumped by hand (see `src/version.ts`); this is the backstop for
   * the time it is forgotten, since an installed PWA is served by a service
   * worker and "did my change reach the phone" is otherwise a guess.
   */
  define: {
    __BUILD_DATE__: JSON.stringify(new Date().toISOString().slice(0, 10)),
  },
  plugins: [
    react(),
    licenceNotice(),
    VitePWA({
      registerType: 'autoUpdate',
      includeAssets: ['apple-touch-icon.png', 'favicon.svg', 'favicon-32.png', 'favicon-64.png'],
      manifest: {
        name: 'Exercise Timer',
        short_name: 'Exercise',
        description: 'Interval timer for gym routines',
        // Matches --ink-900 so the shell does not flash a different colour.
        theme_color: '#121314',
        background_color: '#121314',
        display: 'standalone',
        orientation: 'any',
        // Relative, so an install works the same at a domain root and under a
        // subpath like /exercise-timer/.
        start_url: '.',
        scope: '.',
        icons: [
          { src: 'icon-192.png', sizes: '192x192', type: 'image/png' },
          { src: 'icon-512.png', sizes: '512x512', type: 'image/png' },
          {
            src: 'icon-maskable-512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
      workbox: {
        /*
         * wav for the whistle sample, jpg for the exercise illustrations.
         * Without them the sound and the pictures are fetched at runtime, and the
         * app goes quiet and blank in the one place it matters: a gym with no
         * signal. The 43 plates are ~3MB, deliberately kept at 881px wide so that
         * install stays reasonable. See `scripts/exercise_plates.py`.
         */
        globPatterns: ['**/*.{js,css,html,png,svg,wav,jpg}'],
        // A 42-minute routine can outlast a cached page, so take over
        // immediately rather than waiting for every tab to close.
        clientsClaim: true,
        skipWaiting: true,
      },
    }),
  ],
  test: {
    // Node by default; hook tests opt into jsdom per file with
    // `// @vitest-environment jsdom`.
    environment: 'node',
    include: ['src/**/*.test.{ts,tsx}'],
  },
})
