/**
 * Exercise Timer
 * Copyright (c) 2026 Wayne Davies
 * MIT License. See LICENSE in the project root.
 */

/**
 * The multi-gym half of the exercise table.
 *
 * GENERATED by `scripts/exercise_metadata.py` from the Horizon Torus guide.
 * Do not edit by hand: run the script instead, and put a human decision in
 * its `PATTERN_OVERRIDES` so it survives the next regeneration.
 *
 * Every field but `pattern` is read out of the guide. `area` is the colour of
 * the title band, which the manual's own key defines; `attachment` is named in
 * the instruction text; `perSide` is the instructions saying which limb to
 * start on. `pattern` is derived from the name, because the guide has no notion
 * of push against pull and the generator alternates them.
 */

import type { Exercise } from './exercises'

export const MACHINE_EXERCISES: readonly Exercise[] = [
  { name: 'Lat Pulldown', area: 'upper', pattern: 'pull', equipment: 'machine', media: 'exercises/Lat-Pulldown.jpg', station: 1, attachment: 'lat bar' },
  { name: 'Triceps Press', area: 'upper', pattern: 'push', equipment: 'machine', media: 'exercises/Triceps-Press.jpg', station: 1, attachment: 'lat bar' },
  { name: 'Standard Chest Press', area: 'upper', pattern: 'push', equipment: 'machine', media: 'exercises/Standard-Chest-Press.jpg', station: 2 },
  { name: 'Incline Chest Press', area: 'upper', pattern: 'push', equipment: 'machine', media: 'exercises/Incline-Chest-Press.jpg', station: 2 },
  { name: 'Decline Chest Press', area: 'upper', pattern: 'push', equipment: 'machine', media: 'exercises/Decline-Chest-Press.jpg', station: 2 },
  { name: 'Standing Shoulder Press', area: 'upper', pattern: 'push', equipment: 'machine', media: 'exercises/Standing-Shoulder-Press.jpg', station: 2 },
  { name: 'Seated Row', area: 'upper', pattern: 'pull', equipment: 'machine', media: 'exercises/Seated-Row.jpg', station: 2 },
  { name: 'Seated Cable Row', area: 'upper', pattern: 'pull', equipment: 'machine', media: 'exercises/Seated-Cable-Row.jpg', station: 5, attachment: 'low row bar' },
  { name: 'Deltoid Upright Row', area: 'upper', pattern: 'pull', equipment: 'machine', media: 'exercises/Deltoid-Upright-Row.jpg', station: 5, attachment: 'low row bar' },
  { name: 'Standing Arm Curl', area: 'upper', pattern: 'pull', equipment: 'machine', media: 'exercises/Standing-Arm-Curl.jpg', station: 5, attachment: 'low row bar' },
  { name: 'Reverse Curl', area: 'upper', pattern: 'pull', equipment: 'machine', media: 'exercises/Reverse-Curl.jpg', station: 5, attachment: 'low row bar' },
  { name: 'Bentover Row', area: 'upper', pattern: 'pull', equipment: 'machine', media: 'exercises/Bentover-Row.jpg', station: 5, attachment: 'low row bar' },
  { name: 'Front Shoulder Raise', area: 'upper', pattern: 'push', equipment: 'machine', media: 'exercises/Front-Shoulder-Raise.jpg', station: 5, attachment: 'low row bar' },
  { name: 'Shoulder Shrugs', area: 'upper', pattern: 'pull', equipment: 'machine', media: 'exercises/Shoulder-Shrugs.jpg', station: 5, attachment: 'low row bar' },
  { name: 'Tricep Dips', area: 'upper', pattern: 'push', equipment: 'machine', media: 'exercises/Tricep-Dips.jpg', station: 6 },
  { name: 'Cable Converging Chest Press', area: 'upper', pattern: 'push', equipment: 'machine', media: 'exercises/Cable-Converging-Chest-Press.jpg', station: 7, attachment: 'free-motion' },
  { name: 'Cable Converging Shoulder Press', area: 'upper', pattern: 'push', equipment: 'machine', media: 'exercises/Cable-Converging-Shoulder-Press.jpg', station: 7, attachment: 'free-motion' },
  { name: 'Incline Cable Converging Chest Press', area: 'upper', pattern: 'push', equipment: 'machine', media: 'exercises/Incline-Cable-Converging-Chest-Press.jpg', station: 7, attachment: 'free-motion' },
  { name: 'Cable Fly', area: 'upper', pattern: 'push', equipment: 'machine', media: 'exercises/Cable-Fly.jpg', station: 7, attachment: 'free-motion' },
  { name: 'Seated Cable Arm Curl', area: 'upper', pattern: 'pull', equipment: 'machine', media: 'exercises/Seated-Cable-Arm-Curl.jpg', station: 7, attachment: 'free-motion' },
  { name: 'Seated Cable Tricep Overhead Extension', area: 'upper', pattern: 'push', equipment: 'machine', media: 'exercises/Seated-Cable-Tricep-Overhead-Extension.jpg', station: 7, attachment: 'free-motion' },
  { name: 'Cable Lateral Shoulder Raise', area: 'upper', pattern: 'push', equipment: 'machine', media: 'exercises/Cable-Lateral-Shoulder-Raise.jpg', station: 7, attachment: 'free-motion', perSide: true },
  { name: 'Dynamic Cable Fly', area: 'upper', pattern: 'push', equipment: 'machine', media: 'exercises/Dynamic-Cable-Fly.jpg', station: 7, attachment: 'free-motion', perSide: true },
  { name: 'Dynamic Cable Rear Delt Fly', area: 'upper', pattern: 'pull', equipment: 'machine', media: 'exercises/Dynamic-Cable-Rear-Delt-Fly.jpg', station: 7, attachment: 'free-motion', perSide: true },
  { name: 'Rear Cable Fly', area: 'upper', pattern: 'pull', equipment: 'machine', media: 'exercises/Rear-Cable-Fly.jpg', station: 7, attachment: 'free-motion' },
  { name: 'Seated Abdominal Crunch', area: 'torso', equipment: 'machine', media: 'exercises/Seated-Abdominal-Crunch.jpg', station: 3, attachment: 'ab strap' },
  { name: 'Abdominal Oblique Crunch', area: 'torso', equipment: 'machine', media: 'exercises/Abdominal-Oblique-Crunch.jpg', station: 3, attachment: 'ab strap', perSide: true },
  { name: 'Lower Back Extension', area: 'torso', equipment: 'machine', media: 'exercises/Lower-Back-Extension.jpg', station: 5, attachment: 'low row bar' },
  { name: 'Knee Raise', area: 'torso', equipment: 'machine', media: 'exercises/Knee-Raise.jpg', station: 6 },
  { name: 'Side Cable Bends', area: 'torso', equipment: 'machine', media: 'exercises/Side-Cable-Bends.jpg', station: 7, perSide: true },
  { name: 'Seated Leg Extension', area: 'lower', equipment: 'machine', media: 'exercises/Seated-Leg-Extension.jpg', station: 4 },
  { name: 'Toe Raise', area: 'lower', equipment: 'machine', media: 'exercises/Toe-Raise.jpg', station: 5, attachment: 'low row bar' },
  { name: 'Deadlift', area: 'lower', equipment: 'machine', media: 'exercises/Deadlift.jpg', station: 5, attachment: 'low row bar' },
  { name: 'Standing Leg Curl', area: 'lower', equipment: 'machine', media: 'exercises/Standing-Leg-Curl.jpg', station: 7, perSide: true },
  { name: 'Hip Abductor Leg Raise', area: 'lower', equipment: 'machine', media: 'exercises/Hip-Abductor-Leg-Raise.jpg', station: 7, attachment: 'ankle', perSide: true },
  { name: 'Hip Adductor Leg Raise', area: 'lower', equipment: 'machine', media: 'exercises/Hip-Adductor-Leg-Raise.jpg', station: 7, attachment: 'ankle', perSide: true },
  { name: 'Free-Standing Hamstring Curl', area: 'lower', equipment: 'machine', media: 'exercises/Free-Standing-Hamstring-Curl.jpg', station: 7, attachment: 'ankle', perSide: true },
  { name: 'Glute Kickback', area: 'lower', equipment: 'machine', media: 'exercises/Glute-Kickback.jpg', station: 7, attachment: 'ankle', perSide: true },
  { name: 'Standing Leg Extension', area: 'lower', equipment: 'machine', media: 'exercises/Standing-Leg-Extension.jpg', station: 7, attachment: 'ankle', perSide: true },
  { name: 'Leg Press', area: 'lower', equipment: 'machine', media: 'exercises/Leg-Press.jpg', station: 8 },
  { name: 'Calf Press', area: 'lower', equipment: 'machine', media: 'exercises/Calf-Press.jpg', station: 8 },
]
