/**
 * Exercise Timer
 * Copyright (c) 2026 Wayne Davies
 * MIT License. See LICENSE in the project root.
 */

/**
 * The SHAPE of an instructor routine, read out of the 16 we hold.
 *
 * GENERATED by `scripts/harvest-shapes.test.ts`. Do not edit by hand: run
 * `npm run harvest`.
 *
 * A generator that knows the exercises but not the shape produces a list. These
 * are the ladders the instructor actually writes and the sections she actually
 * names, so what comes out reads like what she sends rather than like arithmetic.
 */

export type LadderShape = {
  /** Reps at each rung, exactly as written. */
  counts: readonly number[]
  /** How many of the 16 routines use it. */
  seen: number
}

/**
 * Used VERBATIM, never generated. `4-9-14-9-4` would be arithmetically fine and
 * unlike anything she has been given; `2-4-6-8-10-8-6-4-2` is what she knows.
 * Commonest first.
 */
export const LADDER_COUNTS: readonly LadderShape[] = [
  { counts: [2, 4, 6, 8, 10, 8, 6, 4, 2], seen: 6 },
  { counts: [1, 2, 3, 4, 5, 4, 3, 2, 1], seen: 5 },
  { counts: [5, 10, 15, 10, 5], seen: 5 },
  { counts: [10, 8, 6, 4, 2, 4, 6, 8, 10], seen: 2 },
  { counts: [20, 16, 12, 8, 4, 8, 12, 16, 20], seen: 2 },
  { counts: [3, 6, 9, 12, 15, 12, 9, 6, 3], seen: 2 },
  { counts: [5, 10, 15, 20, 15, 10, 5], seen: 2 },
  { counts: [10, 15, 20], seen: 1 },
  { counts: [10, 8, 6, 4, 2], seen: 1 },
  { counts: [10, 9, 8, 7, 6, 5, 4, 3, 2, 1], seen: 1 },
  { counts: [12, 8, 4, 8, 12, 16], seen: 1 },
  { counts: [15, 12, 9, 6, 3], seen: 1 },
  { counts: [15, 12, 9, 6, 3, 6, 9, 12, 15], seen: 1 },
  { counts: [2, 4, 6, 8, 10], seen: 1 },
  { counts: [3, 6, 9, 12, 15], seen: 1 },
  { counts: [3, 6, 9, 12, 9, 6, 3], seen: 1 },
  { counts: [4, 8, 12, 16, 20, 16, 12, 8, 4], seen: 1 },
  { counts: [8, 12, 16, 12, 8], seen: 1 },
  { counts: [8, 12, 16, 20, 16, 12, 8], seen: 1 },
]

export type SectionTheme = {
  theme: string
  /** Which body areas belong in it. */
  areas: readonly string[]
  seen: number
}

/**
 * In the order the routines use them, which is the finding: a warm-up first and
 * a finisher last, with the body between. Every routine is a subset of this list
 * in this order.
 */
export const SECTION_THEMES: readonly SectionTheme[] = [
  { theme: 'Warm-up', areas: ['lower', 'upper'], seen: 15 },
  { theme: 'General Body', areas: ['lower', 'torso', 'upper'], seen: 13 },
  { theme: 'Arms & Shoulders', areas: ['upper'], seen: 17 },
  { theme: 'Legs', areas: ['lower'], seen: 15 },
  { theme: 'Core', areas: ['torso'], seen: 14 },
  { theme: 'Finisher', areas: ['lower', 'torso'], seen: 15 },
]

export type SectionFormat = 'standard' | 'emom' | 'interval30' | 'amrap'

export type ThemeFormat = {
  theme: string
  format: SectionFormat
  /** How many of the 16 routines write that theme that way. */
  seen: number
}

/**
 * How she runs each theme, and how often.
 *
 * `standard` is the counted list most sections are. The other three are formats
 * she declares in the heading: an EMOM (a minute an exercise, work then rest out
 * the minute), a 30/30 interval, and an AMRAP (one clock, rounds until it stops).
 * The generator picks from this weighted by `seen`, so they come up about as
 * often as she writes them, which is rarely.
 */
export const SECTION_FORMATS: readonly ThemeFormat[] = [
  { theme: 'Warm-up', format: 'standard', seen: 15 },
  { theme: 'General Body', format: 'standard', seen: 12 },
  { theme: 'General Body', format: 'amrap', seen: 1 },
  { theme: 'Arms & Shoulders', format: 'standard', seen: 16 },
  { theme: 'Arms & Shoulders', format: 'emom', seen: 1 },
  { theme: 'Legs', format: 'standard', seen: 14 },
  { theme: 'Legs', format: 'interval30', seen: 1 },
  { theme: 'Core', format: 'standard', seen: 14 },
  { theme: 'Finisher', format: 'standard', seen: 13 },
  { theme: 'Finisher', format: 'amrap', seen: 1 },
  { theme: 'Finisher', format: 'emom', seen: 1 },
]

/** Routines harvested. Against a theme's `seen`, how often she leaves it out. */
export const ROUTINES = 16

/** Sections in a routine: 6 typical, 5 to 8. */
export const SECTIONS_TYPICAL = 6
export const SECTIONS_MIN = 5
export const SECTIONS_MAX = 8

/** Exercises in a themed section. */
export const SECTION_SIZE = 4

/**
 * Every movement that has opened one of her sessions, folded the way
 * `exercises.prescription.ts` folds names. What a warm-up may be made of.
 */
export const WARM_UP_MOVES: readonly string[] = [
  'alternating front punch',
  'alternating reverse lunge',
  'arm circle',
  'arm swing across chest overhead',
  'bodyweight squat',
  'butt kick',
  'butt stretch',
  'buttkick',
  'cardio',
  'easy bounce',
  'easy jog high knee',
  'fast feet step shuffle',
  'forward backward run',
  'front heel dig',
  'front lift',
  'glute stretch',
  'ham string stretch',
  'hampstring stretch',
  'hamstring curl arm pull',
  'hamstring stretch',
  'high knee lift',
  'inchworm',
  'inchworm shoulder tap',
  'jog on the spot increase the tempo',
  'jogging',
  'jump jump squat',
  'jumping jack',
  'jumping jack tabata timer',
  'knee drive opposite elbow',
  'knee lift',
  'lateral lunge overhead reach',
  'leg swing',
  'march jog on the spot',
  'quad hamstring stretch',
  'quad stretch',
  'rebound',
  'side to side squat with a reach',
  'ski jump side to side jump with feet together',
  'sprint finish fast feet',
  'standing hip rotation torso twist',
  'standing knee hug',
  'torso rotation with arm extended',
  'toy soldier kick',
  'windmill',
  'world s greatest stretch',
  'world s greatest stretch alternate',
]
