/**
 * Exercise Timer
 * Copyright (c) 2026 Wayne Davies
 * MIT License. See LICENSE in the project root.
 */

/**
 * Everything the instructor has written that the hand-authored table does not
 * name.
 *
 * GENERATED by `scripts/harvest-exercises.test.ts` from the routines in
 * `__tests__/emails`. Do not edit by hand: run `npm run harvest`, and put a
 * human decision in that script's `CORRECTIONS` so it survives the next run.
 *
 * `exercises.other.ts` is the hand-authored core, written when there were four
 * routines. This is the rest, found by reading all sixteen. The area and the
 * equipment are read off the name and are usually right; `use` is the least
 * confident of the four fields.
 */

import type { Exercise } from './exercises'

export const HARVESTED_EXERCISES: readonly Exercise[] = [
  { name: 'Around The World', area: 'upper', equipment: 'dumbbell', pattern: 'push' },
  { name: 'Hamstring Stretch', area: 'lower', equipment: 'bodyweight', use: 'mobility' },
  { name: 'Hand-release Push-ups', area: 'upper', pattern: 'push', equipment: 'bodyweight' },
  { name: 'King Squats', area: 'lower', equipment: 'dumbbell' },
  { name: 'Low Plank Hold', area: 'torso', equipment: 'bodyweight' },
  { name: 'Oblique Crunch', area: 'torso', equipment: 'bodyweight' },
  { name: 'Plank Jacks', area: 'torso', equipment: 'bodyweight', use: 'cardio' },
  { name: 'Plie Squats', area: 'lower', equipment: 'bodyweight' },
  { name: 'Quad Stretch', area: 'lower', equipment: 'bodyweight', use: 'mobility' },
  { name: 'Shoulder Press Jacks', area: 'upper', pattern: 'push', equipment: 'bodyweight', use: 'cardio' },
  { name: 'Sit Up Press', area: 'torso', equipment: 'dumbbell' },
  { name: 'Sit Ups', area: 'torso', equipment: 'bodyweight' },
  { name: 'Squat With Front Raise', area: 'lower', equipment: 'dumbbell' },
  { name: 'Stationary Lunge', area: 'lower', equipment: 'bodyweight' },
  { name: 'Straight Legs Up Overhead Crunch', area: 'torso', equipment: 'bodyweight' },
  { name: 'Toe Touch Crunches', area: 'torso', equipment: 'bodyweight' },
]
