/**
 * Exercise Timer
 * Copyright (c) 2026 Wayne Davies
 * MIT License. See LICENSE in the project root.
 */

/**
 * How the instructor prescribes each exercise.
 *
 * GENERATED by `scripts/harvest-prescription.test.ts` from the 16 routines in
 * `__tests__/emails`. Do not edit by hand: run the harvest instead, and add
 * another email if an exercise is missing rather than typing a number in.
 *
 * The table in `exercises.ts` knows what a movement IS. This knows what is
 * asked of it: twelve reps or thirty seconds, and whether it has ever been a
 * ladder's main lift. Medians, because these are round numbers a person chose
 * and the mean of 10 and 20 is 15, which nobody wrote.
 *
 * An exercise absent from here has simply never appeared in a routine we hold.
 */

export type Prescription = {
  name: string
  /** Whichever the instructor uses more often for it. */
  prescribe: 'reps' | 'time'
  reps?: number
  seconds?: number
  /** It has been a ladder's main lift, so it can scale with the rungs. */
  rung?: boolean
}

export const PRESCRIPTIONS: readonly Prescription[] = [
  { name: 'Tricep Dips', prescribe: 'reps', reps: 10 },
  { name: 'Arm Circles', prescribe: 'time', seconds: 30 },
  { name: 'Toy Soldier Kicks', prescribe: 'time', seconds: 40 },
  { name: 'Standing Knee Hugs', prescribe: 'time', seconds: 40 },
  { name: 'Inchworms', prescribe: 'time', seconds: 30 },
  { name: 'World’s Greatest Stretch', prescribe: 'time', seconds: 30 },
  { name: 'Jumping Jacks', prescribe: 'reps', reps: 10, seconds: 30 },
  { name: 'High Knees', prescribe: 'reps', reps: 20, seconds: 30 },
  { name: 'Butt Kicks', prescribe: 'time', seconds: 20 },
  { name: 'Fast Feet', prescribe: 'time', seconds: 30 },
  { name: 'Burpees', prescribe: 'reps', reps: 4, rung: true },
  { name: 'Speed Skaters', prescribe: 'time', rung: true },
  { name: 'Mountain Climbers', prescribe: 'reps', reps: 30, seconds: 30, rung: true },
  { name: 'Cross-Body Mountain Climbers', prescribe: 'reps', reps: 20 },
  { name: 'Front Punches', prescribe: 'reps', reps: 20 },
  { name: 'Uppercuts', prescribe: 'reps', reps: 20 },
  { name: 'Alternating Cross Punches', prescribe: 'reps', reps: 20 },
  { name: 'Easy Bounce', prescribe: 'time', seconds: 30 },
  { name: 'Knee Lifts', prescribe: 'time', reps: 10, seconds: 20 },
  { name: 'Squat to Knee Lift', prescribe: 'time', rung: true },
  { name: 'Jump-Jump Squat', prescribe: 'time', seconds: 30 },
  { name: 'Squats', prescribe: 'time', rung: true },
  { name: 'Squat Pulses', prescribe: 'reps', reps: 12, seconds: 30, rung: true },
  { name: 'Squat Hold', prescribe: 'time', seconds: 30 },
  { name: 'Wall Sit', prescribe: 'time', seconds: 30 },
  { name: 'Sumo Squats', prescribe: 'reps', reps: 12, seconds: 60, rung: true },
  { name: 'Sumo Squat Pulses', prescribe: 'reps', reps: 20 },
  { name: 'Squat Jumps', prescribe: 'reps', reps: 10, seconds: 60, rung: true },
  { name: 'Side-to-Side Squats with a Reach', prescribe: 'time', seconds: 40 },
  { name: 'Walking Lunges', prescribe: 'reps', reps: 5, rung: true },
  { name: 'Reverse Lunges', prescribe: 'reps', reps: 10 },
  { name: 'Alternating Curtsy Lunges', prescribe: 'reps', reps: 10, rung: true },
  { name: 'Alternating Jump Lunges', prescribe: 'reps', reps: 10 },
  { name: 'Bulgarian Split Squats', prescribe: 'time', reps: 5, seconds: 30, rung: true },
  { name: 'Calf Raises', prescribe: 'reps', reps: 15, seconds: 60 },
  { name: 'Glute Bridge Marches', prescribe: 'reps', reps: 15 },
  { name: 'Fire Hydrants', prescribe: 'reps', reps: 15 },
  { name: 'Glute Bridges', prescribe: 'reps', reps: 12 },
  { name: 'Goblet Squats', prescribe: 'reps', reps: 10, seconds: 30, rung: true },
  { name: 'Plank', prescribe: 'time', seconds: 30 },
  { name: 'Forearm Plank', prescribe: 'time', seconds: 30 },
  { name: 'High Plank', prescribe: 'time', seconds: 45 },
  { name: 'Side Plank', prescribe: 'time', seconds: 30 },
  { name: 'Plank Shoulder Taps', prescribe: 'reps', reps: 15, rung: true },
  { name: 'Plank Knee-to-Elbow', prescribe: 'reps', reps: 10 },
  { name: 'Plank Hip Dips', prescribe: 'reps', reps: 10 },
  { name: 'Russian Twists', prescribe: 'reps', reps: 10 },
  { name: 'Bicycle Crunches', prescribe: 'reps', reps: 12, rung: true },
  { name: 'Heel Taps', prescribe: 'reps', reps: 12, rung: true },
  { name: 'Dead Bugs', prescribe: 'reps', reps: 10 },
  { name: 'Reverse Crunches', prescribe: 'reps', reps: 10 },
  { name: 'Flutter Kicks', prescribe: 'reps', reps: 20 },
  { name: 'Hollow Hold', prescribe: 'time', seconds: 20 },
  { name: 'V-Ups', prescribe: 'time', rung: true },
  { name: 'Toe Touches', prescribe: 'reps', reps: 12 },
  { name: 'Alternating Leg Raises', prescribe: 'reps', reps: 10 },
  { name: 'Push-ups', prescribe: 'reps', reps: 10, rung: true },
  { name: 'Shoulder Press', prescribe: 'reps', reps: 10 },
  { name: 'Arnold Press', prescribe: 'reps', reps: 10, seconds: 60 },
  { name: 'Lateral Raises', prescribe: 'reps', reps: 10 },
  { name: 'Tricep Extensions', prescribe: 'time', rung: true },
  { name: 'Bent-Over Rows', prescribe: 'reps', reps: 10, seconds: 60 },
  { name: 'Upright Rows', prescribe: 'reps', reps: 10 },
  { name: 'Bicep Curls', prescribe: 'reps', reps: 12, seconds: 60, rung: true },
  { name: 'Hammer Curls', prescribe: 'reps', reps: 12 },
  { name: 'Band Pull-Aparts', prescribe: 'reps', reps: 15, seconds: 60 },
  { name: 'Bent-Over Reverse Flyes', prescribe: 'reps', reps: 12 },
]
