/**
 * Exercise Timer
 * Copyright (c) 2026 Wayne Davies
 * MIT License. See LICENSE in the project root.
 */

import type { Block, RoutineColour, Workout } from '../engine'
import { SCHEMA_VERSION } from '../engine'
import rawFullBody from './beginner-full-body.routine.json'
import rawStrength from './strength-training.routine.json'

/**
 * The routines seeded into an empty library.
 *
 * Two, and deliberately one of each KIND: a fully timed interval routine and a
 * rep-based strength session. They are the two things the app does, and a new
 * install that only ever saw a countdown would never discover that a step can
 * wait for you.
 *
 * The first one below is the original. One routine, not three. It ships as an
 * authored `Workout` of name, colour and block tree, rather than as a `.tabata`
 * file put through the importer, because
 * it is no longer a straight import: its exercise runs are Reps groups, which the
 * importer deliberately never infers (guessing a routine's shape would silently
 * change someone's workout).
 *
 * The `.tabata` files that used to be seeded are still in this folder as test
 * fixtures for the importer, which is a live feature. See `__tests__/fixtures`.
 * They are not in the app's import graph, so they add nothing to the bundle.
 *
 * The id is STABLE and deliberate: seeding is keyed on it and recorded as "once,
 * ever", so this routine is offered a given install one time and stays deleted if
 * deleted. Keeping the old id means an install that already had it is NOT offered
 * this version. The reps rewrite changes nothing about what plays, so quietly
 * replacing a routine someone may have edited would be the worse trade.
 */
const authored = rawFullBody as { name: string; colour: string; blocks: Block[] }

export const BEGINNER_FULL_BODY: Workout = {
  id: 'seed-beginner-full-body',
  name: authored.name,
  colour: authored.colour as RoutineColour,
  blocks: authored.blocks,
  schemaVersion: SCHEMA_VERSION,
  createdAt: 0,
  updatedAt: 0,
}


/**
 * A real strength session, the instructor's of 20 July 2026, generated by
 * running `pasteFormat.ts` over `__tests__/emails/2026-07-20-general.txt` and
 * committing the result.
 *
 * Generated rather than hand-authored so it cannot drift from what the parser
 * actually produces: it is the app's own worked example of a pasted routine, and
 * an example that no longer matches the parser would be worse than none. To
 * regenerate after a parser change, parse that file and write `{ name, colour,
 * blocks }` back over the JSON. The ids in it are arbitrary but must stay
 * stable, since seeding is keyed on the routine's id and not on theirs.
 *
 * The 20 July one of the three because it needs the least equipment: the others
 * want a trampoline and a set of resistance bands.
 */
const strength = rawStrength as { name: string; colour: string; blocks: Block[] }

export const STRENGTH_TRAINING: Workout = {
  id: 'seed-strength-training',
  name: strength.name,
  colour: strength.colour as RoutineColour,
  blocks: strength.blocks,
  schemaVersion: SCHEMA_VERSION,
  createdAt: 0,
  updatedAt: 0,
}

/**
 * Offered once each, by id. A new seed therefore reaches an install that already
 * exists, which is how the strength routine arrives for someone who has been
 * using the app since before it could run one.
 */
export const SEED_ROUTINES: readonly Workout[] = [BEGINNER_FULL_BODY, STRENGTH_TRAINING]
