/**
 * Exercise Timer
 * Copyright (c) 2026 Wayne Davies
 * MIT License. See LICENSE in the project root.
 */

/**
 * Regenerates src/routines/exercises.shapes.ts from the instructor emails.
 *
 *     npm run harvest
 *
 * The generator can build a circuit. It cannot build the thing Wayne is actually
 * sent, which is six or seven named sections, two or three of them ladders, and
 * most of the steps counted rather than timed.
 *
 * The SHAPE of that is in the corpus as much as the exercises are, so it is read
 * rather than invented:
 *
 *   LADDER_COUNTS   the pyramids the instructor actually writes, commonest
 *                   first. Nineteen of them, and nearly all symmetric. Used
 *                   verbatim: a generated `4-9-14-9-4` would be arithmetically
 *                   fine and unlike anything he has ever been given.
 *
 *   SECTION_THEMES  the headings, in the order they appear. Warm-up, General
 *                   Body, Arms & Shoulders, Legs, Core, Finisher. Every routine
 *                   is a subset of that in that order.
 *
 *   SECTION_SIZE    how many exercises a themed section holds.
 */

import { describe, expect, it } from 'vitest'
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import type { Block } from '../src/engine/types'
import { parseRoutine } from '../src/routines/pasteFormat'

const EMAILS = 'src/routines/__tests__/emails'
const OUT = 'src/routines/exercises.shapes.ts'

/**
 * The themes, and what a heading has to say to count as one.
 *
 * A closed list in the order the routines use, because the ORDER is the finding:
 * a warm-up first and a finisher last, with the body between them. Anything that
 * matches none of these is one of the instructor's one-off headings and is not a
 * theme worth generating.
 */
const THEMES: { theme: string; test: RegExp; areas: string[] }[] = [
  { theme: 'Warm-up', test: /warm[\s-]?up/i, areas: ['lower', 'upper'] },
  { theme: 'General Body', test: /general body/i, areas: ['lower', 'torso', 'upper'] },
  { theme: 'Arms & Shoulders', test: /arms?(\s*&\s*shoulders)?\b|shoulders/i, areas: ['upper'] },
  { theme: 'Legs', test: /^legs?\b/i, areas: ['lower'] },
  { theme: 'Core', test: /core|abs?\b/i, areas: ['torso'] },
  { theme: 'Finisher', test: /finisher|burnout|burner/i, areas: ['lower', 'torso'] },
]

describe('harvest shapes', () => {
  it('writes the ladders and the section skeleton', () => {
    const ladders = new Map<string, number>()
    const themeCounts = new Map<string, number>()
    const sizes: number[] = []
    let routines = 0
    const sectionsPer: number[] = []

    for (const file of readdirSync(EMAILS).filter((f) => f.endsWith('.txt')).sort()) {
      routines += 1
      let sections = 0
      const walk = (blocks: readonly Block[]) => {
        for (const block of blocks) {
          if (block.kind === 'ladder') {
            const key = block.counts.join('-')
            ladders.set(key, (ladders.get(key) ?? 0) + 1)
          }
          if (block.kind === 'section') {
            sections += 1
            const theme = THEMES.find((t) => t.test.test(block.name))?.theme
            if (theme) themeCounts.set(theme, (themeCounts.get(theme) ?? 0) + 1)
            // Exercises, not groups: a ladder counts as the one thing it is.
            if (block.children.length > 1) sizes.push(block.children.length)
          }
          if (block.kind !== 'segment') walk(block.children)
        }
      }
      walk(parseRoutine(readFileSync(`${EMAILS}/${file}`, 'utf8'), file).blocks)
      sectionsPer.push(sections)
    }

    const ordered = [...ladders.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    const median = (values: number[]) =>
      [...values].sort((a, b) => a - b)[Math.floor((values.length - 1) / 2)]!

    console.log(`${routines} routines`)
    console.log(`  ladder shapes    : ${ordered.length}`)
    console.log(`  sections each    : ${median(sectionsPer)} typical, ${Math.min(...sectionsPer)} to ${Math.max(...sectionsPer)}`)
    console.log(`  exercises a piece: ${median(sizes)} typical`)
    for (const { theme } of THEMES) console.log(`      ${theme}: ${themeCounts.get(theme) ?? 0}`)

    const rungs = ordered
      .map(([counts, seen]) => `  { counts: [${counts.split('-').join(', ')}], seen: ${seen} },`)
      .join('\n')
    const themes = THEMES.map(
      ({ theme, areas }) =>
        `  { theme: '${theme}', areas: [${areas.map((a) => `'${a}'`).join(', ')}], seen: ${themeCounts.get(theme) ?? 0} },`,
    ).join('\n')

    writeFileSync(
      OUT,
      `/**
 * Exercise Timer
 * Copyright (c) 2026 Wayne Davies
 * MIT License. See LICENSE in the project root.
 */

/**
 * The SHAPE of an instructor routine, read out of the ${routines} we hold.
 *
 * GENERATED by \`scripts/harvest-shapes.test.ts\`. Do not edit by hand: run
 * \`npm run harvest\`.
 *
 * A generator that knows the exercises but not the shape produces a list. These
 * are the ladders the instructor actually writes and the sections he actually
 * names, so what comes out reads like what he sends rather than like arithmetic.
 */

export type LadderShape = {
  /** Reps at each rung, exactly as written. */
  counts: readonly number[]
  /** How many of the ${routines} routines use it. */
  seen: number
}

/**
 * Used VERBATIM, never generated. \`4-9-14-9-4\` would be arithmetically fine and
 * unlike anything he has been given; \`2-4-6-8-10-8-6-4-2\` is what he knows.
 * Commonest first.
 */
export const LADDER_COUNTS: readonly LadderShape[] = [
${rungs}
]

export type SectionTheme = {
  theme: string
  /** Which body areas belong in it. */
  areas: readonly string[]
  seen: number
}

/**
 * In the order the routines use them, which is the finding: a warm-up first and
 * a finisher last, with the body between. Every routine is a subset of this list
 * in this order.
 */
export const SECTION_THEMES: readonly SectionTheme[] = [
${themes}
]

/** Sections in a routine: ${median(sectionsPer)} typical, ${Math.min(...sectionsPer)} to ${Math.max(...sectionsPer)}. */
export const SECTIONS_TYPICAL = ${median(sectionsPer)}
export const SECTIONS_MIN = ${Math.min(...sectionsPer)}
export const SECTIONS_MAX = ${Math.max(...sectionsPer)}

/** Exercises in a themed section. */
export const SECTION_SIZE = ${median(sizes)}
`,
      'utf8',
    )
    expect(ordered.length).toBeGreaterThan(10)
  })
})
